### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by braindome** [braindome/Tre-i-rad#1]
- [x] #todo ⏫ Felhantering inputtyp. ✅ 2022-09-30
- [x] #todo ⏫ Felhantering OutOfBounds. ✅ 2022-09-30
- [x] #todo 🔼 Spelet börjar om när en spelare vunnit.
- [x] #todo 🔼 Räkna hur många vinster varje spelare har.
- [x] #todo 🔼 Datorspelare (slumpade drag) **ELLER** välja hur många rutor spelplanen har.

**Comment by braindome** [comment]
Complete.
